### ISSUE TITLE
Pleiades202309でHTMLエディターが使用できない

### ISSUE THREAD

**Issue by y-skrb** [cypher256/pleiades.io#152]
お世話になっております。

以下のとおり、202309からHTMLエディターで、通常のテキストエディターと同様（構造色分け無し、コンテンツアシスト無効）になってしまっています。
※202212では通常通り動作するのは確認しており、2023のいつからか動作しなくなっているようです。

対応方法等あればご教授ください。

![image](https://github.com/cypher256/pleiades.io/assets/46509195/70ba1d14-17da-4f55-a3f7-ea106450c911)

**Comment by cypher256** [comment]
標準の Eclipse IDE for Enterprise Java and Web Developers でも発生していて、解決されていないようです。
(このチケットは css ですが、html も同じかと思います)
[Bug 582460](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582460) - Syntax highlighting in CSS-Editor broken since 2023-06

Pleiades 側では対応できそうにありません。
Red Hat の汎用テキスト・エディターはアクティブに開発されていますが、
本家 WTP は最近活動がかなり少なくなってしまっています。
他の Eclipse プロジェクトに追随して、WTP プロジェクトも来年 github に移行するので、
対応されるとすれば、そこからかもしれません。

**Comment by y-skrb** [comment]
ありがとうございます。
※Pleiades側ではないだろうなと思いつつ・・・本家のバグ情報を教えていただき助かりました。
ひとまず本家側での対応を待つということで、こちらはクローズします。

**Comment by cypher256** [comment]
Eclipse 2023-12 で解消されていました。
https://bugs.eclipse.org/bugs/show_bug.cgi?id=582460
